### ISSUE TITLE
Add Internationalization

### ISSUE THREAD

**Issue by shaynelightfoot** [xkisu/craftcookieconsent#1]
The fields in the plugin settings cannot be translated. Wrapping the ouput of each field with `Craft::t()` would allow translation of the fields through translation files.
https://craftcms.com/docs/plugins/internationalization
I am not too familiar with git, which is why I have submitted an issue instead of a pull request.

**Comment by xkisu** [comment]
Gotcha, I'll get onto adding/fixing that as soon as I can. (Expect to see something Monday at the earliest)

**Comment by shaynelightfoot** [comment]
Any update on this? I have made the changes I suggested to my own project, but it requires an extra step to add/change translations (modifying the translations file). I think further development of this feature to allow locale options within the admin settings would be better. Do you have plans to develop on this?

**Comment by xkisu** [comment]
Sorry, I meant to get to this sooner but some stuff came up 😉 

I read the documentation page you liked to, but I am somewhat confused as to what I need to do to make localization work. My settings template runs all the display labels through the `t` so I thought that was enough. 

Could you tell me some could line numbers in a file or show a small example of what I need to do so I can get a better idea of what needs to be changed?

**Comment by shaynelightfoot** [comment]
You've translated the labels, but not the user defined content. The values for the fields "Learn More Link", "Learn More Text", "Message" and "Dismiss Button Text" are not passed through the `Craft::t()` filter.

In CraftCookieConsentPlugin.php, lines 76-79, change this:
```
"message": "'. $settings->message .'",
"dismiss": "'. $settings->dismiss .'",
"link": "'. $settings->learn .'",
"href": "'. $settings->learn_more_link .'"
```
to this:
```
"message": "'. Craft::t($settings->message) .'",
"dismiss": "'. Craft::t($settings->dismiss) .'",
"link": "'. Craft::t($settings->learn) .'",
"href": "'. Craft::t($settings->learn_more_link) .'"
```
Now the user can translate the values of these fields by creating/updating the files in their craft/translations folder, just as they would for static text in a template.
https://craftcms.com/support/static-translations

I was hoping that this would ultimately be possible using the native Craft locale switcher to avoid the extra step of creating/updating the translation files. However, after some quick research, I don't think this feature is available to plugins (although I may be wrong).

**Comment by xkisu** [comment]
Done. Thanks for helping me out with that!

**Comment by LukasKnuthImagineOn** [comment]
This should be documented in the Readme. I was about to implement this when I found the bug.
