### ISSUE TITLE
Ajax Interferance

### ISSUE THREAD

**Issue by matt-adigital** [xkisu/craftcookieconsent#2]
Hi,

When ajax loading a page where we are returning a json array, cookie consent is adding in link and style tags and breaking our json formatting. I've updated the plugin file by wrapping everything inside the init function with a simple conditional before the resources are included:
`if (!craft()->request->isAjaxRequest) {`
Could this please be added to the next version release so that ajax requests are no longer interfered with?
Thank you!

**Comment by xkisu** [comment]
Somehow I missed your issue, sorry about that! I'll take a look at adding this asap

**Comment by xkisu** [comment]
Fixed d186e02ea5cc620628a97704576f0053781132da

**Comment by matt-adigital** [comment]
Thank you for implementing the fix. I've been testing it and it works on some pages but not others because when the resources are loaded in it forces the document to be html and breaks a url that returns a simple json array.

Moving the condition above the includeCssResource line fixes this though for both request types and doesn't break the plugin settings page.

**Comment by xkisu** [comment]
Oh that's interesting, I would have assumed that Craft would detect it's an Ajax request and wouldn't allow that. 

I'll take a look at this as soon as I can

**Comment by matt-adigital** [comment]
I would have thought so too but sadly it seems not, it's caught me out also with a plugin I wrote. Thank you for your time on this though, it's much appreciated

**Comment by xkisu** [comment]
Fixed! 12dbf913402d065b831eced1d33f5fe47152adc5
