### ISSUE TITLE
Multi languages

### ISSUE THREAD

**Issue by pieterjandebruyne** [xkisu/craftcookieconsent#6]
Hi,

Is it possible to display different messages for different locales? Or is it for example possible to put twig code in the field to use something like the translate plugin ( https://github.com/boboldehampsink/translate ).

Thx

**Comment by pieterjandebruyne** [comment]
Ok found it, you can paste the string inside craft's translations files ( https://craftcms.com/support/static-translations )

**Comment by samverdyck** [comment]
@pieter-janDB, can you explain how you did this exactly? I understand how to create a translation file, but how to implement in the plugin?
