### ISSUE TITLE
Doesn't support the Craft 3.1 project config yaml file

### ISSUE THREAD

**Issue by toddpadwick** [xkisu/craftcookieconsent#7]
Using project.yaml requires adminstration access to be revoked on production and staging. This means that there is no way to currently add/edit the cookie text in anything other than dev/local and copy the database over.
Will there be support for this anytime soon?

**Comment by xkisu** [comment]
As per the readme this plugin was not tested with Craft 3.1, so if it does work then it is unsupported.

**Comment by toddpadwick** [comment]
Sorry, my fault this was not the plugin i meant to comment on. There is a plugin with the same name which was made for craft 3 so i closed the issue.  Thanks for responding so quick though.
